# Generated by Django 6.0.2 on 2026-02-09 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('address_number', models.CharField(max_length=5)),
                ('birthday', models.DateField(verbose_name='Date of birth')),
                ('place_of_birth', models.CharField(max_length=100)),
                ('fiscal_code', models.CharField(max_length=11)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alby_intelligence.contracts')),
            ],
        ),
    ]
