# Generated by Django 6.0.2 on 2026-02-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alby_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='enabled',
            field=models.BooleanField(null=True),
        ),
    ]
